# Generated by Django 5.1.2 on 2024-10-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autoreply_delay',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
